---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10  
    target-branch: "dependencies-updates" 
#    labels: ["dependencies", "bump"]
    labels: ["dependencies"]
    commit-message:
      prefix: "dependencies: "

  - package-ecosystem: terraform
    directory: "terraform/images-projects/brands/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: "dependencies-updates" 
#    labels: ["dependencies", "bump"]
    labels: ["dependencies"]
    commit-message:
      prefix: "dependencies: "
      
  - package-ecosystem: terraform
    directory: "terraform/images-projects/backend/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: "dependencies-updates" 
#    labels: ["dependencies", "bump"]
    labels: ["dependencies"]
    commit-message:
      prefix: "dependencies: "
      
  - package-ecosystem: terraform
    directory: "/terraform/coins-projects/envs/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: "dependencies-updates" 
#    labels: ["dependencies", "bump"]
    labels: ["dependencies"]
    commit-message:
      prefix: "dependencies: "

