---
version: 2

registries:
 spacelift:
   type: terraform-registry
   url: https://app.spacelift.io
   token: ${{ secrets.SPACELIFT_TOKEN }}
   
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10  
    labels: ["dependencies"]
    commit-message:
      prefix: "dependencies: "

      
  - package-ecosystem: terraform
    directory: "examples/basic"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: ["dependencies"]
    commit-message:
      prefix: "dependencies: "
      
  - package-ecosystem: terraform
    directory: "/"
    registries:
     - spacelift
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: ["dependencies"]
    commit-message:
      prefix: "dependencies: "
