---
name: Release Drafter


on:
  workflow_dispatch:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master 
  pull_request:
  pull_request_target:


permissions:
  contents: read
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
          
      - uses: release-drafter/release-drafter@v6.0.0
        with:
          config-name: configs/draft-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
