name: Auto Label


on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  labeler:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v1.5.0 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/labeler.yml
