---
name: Release


on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: version
        id: version
        run: |                  
         "tag=${GITHUB_REF/refs\/tags\//}"
         "version=${tag#v}"
         "major=${version%%.*}"
         {  echo "tag=${tag}";
            echo "version=${version}";
            echo "major=${major}";
         } >> $GITHUB_OUTPUT        
          
          
          
#       - name: version
#         id: version
#         run: |                  
#          tag=${GITHUB_REF/refs\/tags\//}
#          version=${tag#v}
#          major=${version%%.*}
#          echo "tag=${tag}" >> $GITHUB_OUTPUT
#          echo "version=${version}" >> $GITHUB_OUTPUT
#          echo "major=${major}" >> $GITHUB_OUTPUT          
          
      - uses: release-drafter/release-drafter@v5.21.1
        with:
          publish: true
          version: ${{ steps.version.outputs.version }}
          config-name: configs/draft-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: force update major tag
        run: |
          git tag v${{ steps.version.outputs.major }} ${{ steps.version.outputs.tag }} -f
          git push origin refs/tags/v${{ steps.version.outputs.major }} -f
          
