name: 'TERRATEST'

            
on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]
    types: [opened, synchronize, reopened, closed, labeled, unlabeled]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
  
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Run Terratest
        uses: cloudposse/github-action-terratest@main
        with:
          sourceDir: test/src
          
